### ISSUE TITLE
View Discrimination incident Map is not updated in sync with the incidents reported

### ISSUE THREAD

**Issue by jeslinger-wisc** [IoT-testersgroup/ripple#12]
After reporting an incident at a particular location I navigate back to the View Discrimiantion incident map and on clicking all the incidents reported are shown in Washington and not at the location reported I would have to search for Madison else it appears after as if there are no cases reported in Madison

Severity: Medium-high

Suggestion: Update both the map after reporting the incident and the discrimiantion incident map synchronously and make the markers visible without searching.

**Comment by tituscsmith** [comment]
Connected to other issues with onRegionChange Complete. Fixed with same fix.
