### ISSUE TITLE
Only show the latest incident at the same location

### ISSUE THREAD

**Issue by jeslinger-wisc** [IoT-testersgroup/ripple#13]
When two different incidents are entered, the normal map will only show one pinpoint (the latest incident will cover all the previous ones). However, the heat map seems to be showing all incidents.

Severity: Medium

Suggestion: There are two approaches that can be made. The first suggestion is that displaying all the pinpoints around the location shows it won’t be covered (although it might look less neat). The second approach will be showing only a pinpoint and notify the users that there were more than one incidents happened at that specific location and allow users to click to view more details.

**Comment by tituscsmith** [comment]
This is a noted bug but is beyond the scope of this semester unfortunately due to time constraints.
