### ISSUE TITLE
The default map location is at Washington D.C. no matter where the user current location is.

### ISSUE THREAD

**Issue by jeslinger-wisc** [IoT-testersgroup/ripple#19]
The user has to manually drag and search his/her location when viewing the map, which might be not user-friendly to make the user take extra steps to view the incident around him/her.

Severity: Medium

Suggestion: Track the GPS location of the user and auto direct to that location every time when the user clicks maps.

**Comment by tituscsmith** [comment]
Feature Added! Used the Expo location library
