### ISSUE TITLE
Google Maps Search Bar Covered + Acting Funny

### ISSUE THREAD

**Issue by jeslinger-wisc** [IoT-testersgroup/ripple#3]
On Google Maps page, Search bar to search for a location is partially covered up by the two buttons labelled "Heatmap" and "SupportInfo". While the search bar can still be accessed and used, it seems to behave strangely- Typing in St. Louis brings user view to west Chicago, St. Paul brings the user view to southern Mississippi, etc.

Severity: Medium-Low (not huge deal, though the search bar is inconvenient in two different ways)

The "covered up by buttons" issue may again be a recorded size vs. actual size issue (which also could be linked to the phone brand/make/model). The search issue could be a general issue with Goggle Maps API (possibly unique to phones), though also could be some sort of handling issue between getting and using the supplied string.

**Comment by tituscsmith** [comment]
Fixed!
