### ISSUE TITLE
Incident Markers Only Show Up Based on Search Bar

### ISSUE THREAD

**Issue by jeslinger-wisc** [IoT-testersgroup/ripple#4]
While incidents for a region are shown after the user view is brought over it (by the search bar feature), other events around the entire map do not show up if the user manually pans over to a different region (i.e. searching Madison, then panning over to Washington D.C. does not show the three reported incidents previously shown there until Washington D.C. is re-searched)

Severity: Low

More just of a convenient/aesthetic feature given panning is an option on the map. Could try checking if the user has moved a certain amount away from the searched area and then recall whatever function displays nearby markers.

**Comment by tituscsmith** [comment]
Fixed with automatic server for onRegionChangeComplete
