### ISSUE TITLE
when the user searches a city and clicks on the heat map button, the app crashes and closes with an error.

### ISSUE THREAD

**Issue by jeslinger-wisc** [IoT-testersgroup/ripple#6]
we tested this by trying to search for “Las Vegas”, “St Louis”, “Nashville”, and a few other cities and the error always occurred. When we type the city name into the search bar it brings us to those cities on the map. If we click the “Heat Map” button, the app crashes and the error says “No input points”. We interpret this to mean that if the user clicks to see the heat map of a city without any incident reports, the app crashes and shuts down.

Severity: blocker

look where the heat map is called from. Follow the lines that are included in the error to trace back where you call the heat map and see what values are inputted into the heat map view function. Make it so that if there are no reports in the view of the heat map that the error is handled properly. Possibly trigger an alert stating “no incidents in this area have been reported” or something similar.

**Comment by tituscsmith** [comment]
Attempted to replicate on multiple machines and not possible. Possibly fixed as a byproduct of other fixes.
